#!/usr/bin/env bash
# Using the /redirect_me configuration of nginx
# Redirection is a "301 Moved Permanetly"

sudo apt-get update -y
sudo apt install nginx -y

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com;}' /etc/nginx/sites-available/default
sudo service nginx start
