#!/usr/bin/env bash
# A bash script that configures the Nginx server so that
# /redirect_me points to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# adding the redirection line
sudo sed -i "48i\\\tif (\$request_filename ~ redirect_me){\n\t\t\
rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}" /etc/nginx/sites-available/default

sudo service nginx restart
