#!/usr/bin/env bash
# returns a custom header on request

# updatee then insta nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# replacing lines
sudo sed -i "32i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo service nginx start
