#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd.
# It displays only:
# username, user id, Home directory path for the user

while read -r data
do
	echo "$data" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
