#!/usr/bin/env bash
# A a Bash script that displays numbers from 1 to 20 with some mods

dgt=1

while [ $dgt -le 20 ]
do
  echo "$dgt"
  case $dgt in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  ((dgt++))
done
